[functions]
  directory = ".netlify/functions"
  external_node_modules = [
  "express",
  "serverless-http",
  "bcrypt",
  "cors",
  "dotenv",
  "express-mongo-sanitize",
  "express-rate-limit",
  "express-validator",
  "helmet",
  "jsonwebtoken",
  "mongodb",
  "mongoose",
  "xss-clean",
  "multer",
  "cloudinary"
  ]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
